---
meta:
  name:    cron
  release: cron
  target:  sw
  url:     https://ci.vsphere.starkandwayne.com

  initial_version: 0.1.0

  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: cron-warden

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   cron-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/cron-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/cron-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/cron-boshrelease/slack:webhook" ))
    channel: '#botspam'
